options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 🧪 Run tests
  - name: 'python:3.12-slim'
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r requirements.txt
        pytest

  # 🐳 Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build', '-t',
        'us-central1-docker.pkg.dev/steel-utility-459421-h2/questlog-repo/questlog-image:$SHORT_SHA',
        '.'
      ]

  # ☁️ Docker push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/steel-utility-459421-h2/questlog-repo/questlog-image:$SHORT_SHA'
      ]

  # 🚀 Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - questlog-service
      - --image=us-central1-docker.pkg.dev/steel-utility-459421-h2/questlog-repo/questlog-image:$SHORT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

